rss/urls.py
from django.urls import path
from . import views

app_name = 'rss'
urlpatterns = [
    path('', views.CreateFeedView.as_view(), name='index'),
    path('dynamic', views.CreateDynamicView.as_view(), name='create_dynamic'),
    path('list', views.FeedListView.as_view(), name='feed_list' ),
    path('<int:pk>', views.FeedDetailView.as_view(), name='feed_detail'),
    path('<int:pk>/createfeed', views.CreateConsumableView.as_view(), name='create_consumable'),
    path('<int:feed_id>/feeds/<int:pk>', views.ConsumableDetailView.as_view() , name='consumable_detail'),
    path('<int:feed_id>/feeds/<int:pk>/feed', views.FeedRSSView() , name='feed_rss'),

]

rss_restart/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('rss.urls')),
    path('admin/', admin.site.urls),
]

rss/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator, URLValidator
from django.urls import reverse

# Create your models here.
class RSSFeed(models.Model):
    title = models.TextField()
    description = models.TextField(blank=True)
    length = models.PositiveIntegerField()
    def get_absolute_url(self):
        return reverse('rss:feed_detail', kwargs={'pk':self.pk})

class DynamicFeed(RSSFeed):
    origin_link = models.TextField(validators=[URLValidator], blank=True)
    last_modified= models.DateField(auto_now=True)
    active = models.BooleanField(default=True)

class ConsumableFeed(models.Model):
    feed = models.ForeignKey('RSSFeed', on_delete=models.CASCADE)
    marker = models.PositiveIntegerField(default=0)
    daily_items = models.PositiveIntegerField(default=1, validators=[MinValueValidator(1), MaxValueValidator(10)])
    # date_created = models.DateField(auto_now_add=True)
    # date_modified = models.DateField(auto_now=True)
    def get_absolute_url(self):
        return reverse('rss:consumable_detail', kwargs={'pk':self.pk, 'feed_id':self.feed.id})

    def get_rss_url(self):
        return reverse('rss:feed_rss', kwargs={'pk':self.pk, 'feed_id':self.feed.id})

class RSSItem(models.Model):
    #allow the user to add a list of own titles/descs
    #or default description to nothing and title to url

    ordinal = models.PositiveIntegerField()
    feed = models.ForeignKey('RSSFeed', on_delete=models.CASCADE)
    content_link = models.TextField(validators=[URLValidator])
    description = models.TextField(blank=True)
    title = models.TextField(blank=True)

rss/forms.py
from django import forms
from django.core.validators import URLValidator
from django.core.exceptions import ValidationError

class URLList(forms.Field):
    def to_python(self, value):
        if not value:
            return []
        return [s.strip() for s in value.splitlines() if s.strip()]

    def validate(self, value):
        super().validate(value)
        error_list = []
        for link in value:
            try:
                URLValidator(message=f'\'{link}\' is not a valid url.')(link)
            except ValidationError as err:
                error_list.append(err)
                print(err)
        if error_list:
            raise ValidationError(error_list)

class RSSForm(forms.Form):
    title = forms.CharField(label='Name your list:')
    description = forms.CharField(label='Optionally describe your content (this will appear in the description section of the rss feed):', required=False)
    item_links = URLList(widget=forms.Textarea, label='URLs go here:')
    reverse = forms.BooleanField(label='Publish in reverse.', required=False)

class DynamicForm(RSSForm):
    origin_link = forms.URLField(label="Origin link")

    def clean_origin_link(self):
        data = self.cleaned_data['origin_link']
        return data

class ConsumableForm(forms.Form):
    daily_items = forms.IntegerField(min_value=1, max_value=10, initial=1)

rss/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import edit, detail, list, base
from rss.models import RSSFeed, RSSItem, ConsumableFeed, DynamicFeed
from rss.forms import RSSForm, ConsumableForm, DynamicForm
from django.contrib.syndication.views import Feed
from django.urls import reverse
from datetime import timedelta, date
from django.core.paginator import Paginator
import feedparser

# Create your views here.
def index(request):
    return HttpResponse('View create')

# class CreateItemView(edit.FormView):
#     template_name = 'rss/rssitem_form.html'
#     form_class = RSSItemForm
#
#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#
#     def form_valid(self, form):
#         link = form.cleaned_data['link']
#         descr = form.cleaned_data['description']
#
#         feed = RSSFeed.objects.get(id = self.kwargs['pk'])
#         ord = RSSItem.object.filter(feed=feed).count()
#         for ind, link in enumerate(form.cleaned_data['item_links']):
#             ord+=1
#             RSSItem.objects.create(feed=created_feed, content_link = link, title=form.cleaned_data['titles'][ind], description=form.cleaned_data['desc'][ind], ordinal=ord)

class CreateConsumableView(edit.FormView):
    template_name = 'rss/consumable_form.html'
    form_class = ConsumableForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['feed'] = RSSFeed.objects.get(id=self.kwargs['pk'])
        return context

    def form_valid(self, form):
        feed = RSSFeed.objects.get(id = self.kwargs['pk'])
        num_items = form.cleaned_data['daily_items']
        created = ConsumableFeed.objects.create(feed=feed, daily_items=num_items)
        return HttpResponseRedirect(reverse('rss:consumable_detail', kwargs={'pk':created.pk, 'feed_id':created.feed.id}))

class CreateFeedView(edit.FormView):
    template_name = 'rss/rssfeed_form.html'
    form_class = RSSForm

    def form_valid(self, form):
        feed_title = form.cleaned_data['title']
        feed_description = form.cleaned_data['description']

        created_feed = RSSFeed.objects.create(title=feed_title, description=feed_description, length=len(form.cleaned_data['item_links']))

        for ind, link in enumerate(reversed(form.cleaned_data['item_links']) if form.cleaned_data['reverse'] else form.cleaned_data['item_links']):
            RSSItem.objects.create(feed=created_feed, content_link = link, ordinal=ind+1)

        return HttpResponseRedirect(reverse('rss:feed_detail', kwargs={'pk':created_feed.pk}))

class CreateDynamicView(CreateFeedView):
    template_name = 'rss/dynamicfeed_form.html'
    form_class = DynamicForm

    #form_valid should be the same
    #cleaning the form to make sure the origin link is valid should be only difference


class ConsumableDetailView(detail.DetailView):
    model = ConsumableFeed

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

delete_age=7
class FeedDetailView(detail.DetailView):
    model = RSSFeed

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        feed_links = RSSItem.objects.filter(feed=self.object).order_by('ordinal')
        page_number = self.request.GET.get('page')
        pages = Paginator(feed_links, 25)
        context['page_obj'] = pages.get_page(page_number)
        context['total_count'] = pages.count
        return context

class FeedListView(list.ListView):
    model = RSSFeed

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        feeds = RSSFeed.objects.all().order_by('title')
        page_number = self.request.GET.get('page')
        pages= Paginator(feeds, 25)
        context['page_obj'] = pages.get_page(page_number)
        context['total_count'] = pages.count
        return context

class FeedRSSView(Feed):
    def get_object(self, request, feed_id, pk):
        return ConsumableFeed.objects.filter(feed=feed_id).get(pk=pk)

    def title(self, obj):
        return obj.feed.title

    def link(self, obj):
        return obj.feed.get_absolute_url()

    def description(self, obj):
        return obj.feed.description

    def items(self, obj):
        items = RSSItem.objects.filter(feed=obj.feed)

        if obj.marker <= obj.feed.length:
            return items.filter(ordinal__range=(obj.marker-9,obj.marker)).order_by('ordinal')#[:10]
        else:
            return items.order_by('ordinal')[obj.feed.length-10:obj.feed.length]

    def item_link(self, item):
        return item.content_link

    def item_title(self, item):
        if item.title:
            return item.title
        else:
            return item.content_link

    def item_description(self, item):
        if item.description:
            return item.description
        else:
            return item.content_link

rss/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>
      url-rss -
      domonicmilesi.com
    </title>

    <meta charset="utf-8">
    <meta name="author" content="Domonic Milesi" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="shortcut icon" href="/favicon.png">
    <link rel="stylesheet" type="text/css" href="{% static 'rss/style.css' %}" />
  </head>

  <body>
    <header>&nbsp;<a href="{% url 'rss:feed_list' %}">browse</a> &nbsp; <a href="{% url 'rss:index' %}">create</a> &nbsp; <a href="https://domonicmilesi.com/"> back to domonicmilesi.com</a> <whitespace></header>
    <main class="content container">
      {% block errors %}{% endblock %}
      {% block content %}{% endblock %}
    </main>
  </body>
</html>

rss/templates/rss/consumable_form.html
{% extends "base.html" %}

{% block content %}
<h1>This is where you create an RSS feed for <a href="{% url 'rss:feed_detail' feed.id %}">{{ feed.title }}</a>.</h1>
<form method="post">{% csrf_token %}
  <p>
    <label for="id_daily_items">The feed will publish this many items per day (1-10):</label>
    <input type="number" name="daily_items" value="1" min="1" max="10" required="" id="id_daily_items">
  </p>
  <input type="submit" value="Create">
</form>
{% endblock %}

rss/templates/rss/consumablefeed_detail.html
{% extends "base.html" %}

{% block content %}
<h1>This is where you subscribe to <a href="{% url 'rss:feed_detail' object.feed.id %}">{{ object.feed.title }}</a>.</h1>
<h2>This link goes into your RSS Reader: <br><a href="{{ object.get_rss_url }}">{{ request.get_host }}{{object.get_rss_url}}</a></h2>
<p>Every day, this feed  will publish {{ object.daily_items }} link{% if object.daily_items > 1 %}s{% endif %}. A week after all the links are published, the feed gets deleted.</p>
{% endblock %}

rss/templates/rss/dynamicfeed_form.html
{% extends "base.html" %}
{% block errors %}
  {{ form.non_field_errors }}
{% endblock %}

{% block content %}
<h1>
  This is a tool for creating an RSS feed out of a list of urls.
</h1>
<p>
  You supply a list of URLs here; then I can generate an RSS feed for you that publishes these URLs one by one.
<p>
<p>This is useful for working through blog archives. Think of it as similar to re-airing a TV show. </p>
<form method="post">{% csrf_token %}
  <p>
    {{ form.title.errors }}
    {{ form.title.label_tag }}
    {{ form.title }}
  </p>
  <p>
    {{ form.description.errors }}
    {{ form.description.label_tag }}
    {{ form.description }}
  </p>
  <p>
    {{ form.origin_link.errors }}
    {{ form.origin_link.label_tag }}
    {{ form.origin_link }}
  </p>
  <p>
    {{ form.item_links.errors }}
    {{ form.item_links.label_tag }}
    {{ form.item_links }}
  </p>
  <p>
    RSS feed will publish the URLs above from the first line down. You can reverse this and publish from the last line up instead.
    <br>
    {{ form.reverse.errors }}
    {{ form.reverse }}
    {{ form.reverse.label_tag }}
  </p>
  <input type="submit" value="Create">
</form>
{% endblock %}

rss/templates/rss/rssfeed_detail.html
{% extends "base.html" %}

{% block content %}
<h1>This is {{object.title}}</h1>
<p>{{object.description}}</p>
<h2>You can subscribe to an <a href="{% url 'rss:create_consumable' object.id %}">RSS feed that publishes these links</a>.</h2>

<h3>These are the URLs, numbered in the order they'll be published in.</h3>
<ul style="list-style-type:decimal;">
  {% for link in page_obj %}
    <li><a href="{{link.content_link}}">{{link.content_link}}</a></li>
  {% endfor %}
</ul>
<div>
    <span>
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
        <span>
          {{page_obj.start_index}}-{{page_obj.end_index}} of {{total_count}} URLs; page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}

rss/templates/rss/rssfeed_form.html
{% extends "base.html" %}
{% block errors %}
  {{ form.non_field_errors }}
{% endblock %}

{% block content %}
<h1>
  This is a tool for creating an RSS feed out of a list of urls.
</h1>
<p>
  You supply a list of URLs here; then I can generate an RSS feed for you that publishes these URLs one by one.
<p>
<p>This is useful for working through blog archives. Think of it as similar to re-airing a TV show. </p>
<form method="post">{% csrf_token %}
  <p>
    {{ form.title.errors }}
    {{ form.title.label_tag }}
    {{ form.title }}
  </p>
  <p>
    {{ form.description.errors }}
    {{ form.description.label_tag }}
    {{ form.description }}
  </p>
  <p>
    {{ form.item_links.errors }}
    {{ form.item_links.label_tag }}
    {{ form.item_links }}
  </p>
  <p>
    RSS feed will publish the URLs above from the first line down. You can reverse this and publish from the last line up instead.
    <br>
    {{ form.reverse.errors }}
    {{ form.reverse }}
    {{ form.reverse.label_tag }}
  </p>
  <input type="submit" value="Create">
</form>
{% endblock %}

rss/templates/rss/rssfeed_list.html
{% extends "base.html" %}

{% block content %}
<h1>This is where you browse lists other people have made.</h1>
<ul style="list-style-type:none;">
  {% for feed in page_obj %}
    <li>
      {% if feed.description %}
      <details>
        <summary><a href="{{feed.get_absolute_url}}">{{feed.title}}</a></summary>
          {{feed.description}}
      </details>
      {% else %}
        <a href="{{feed.get_absolute_url}}">{{feed.title}}</a>
      {% endif %}
    </li>
  {% endfor %}
</ul>
<div>
    <span>
        {% if page_obj.has_previous %}
          <a href="?page=1">&laquo; first</a>
          <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}
        <span>
          {{page_obj.start_index}}-{{page_obj.end_index}} of {{total_count}} feed{% if total_count > 1 %}s{% endif %}; page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>
        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number }}">next</a>
          <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock %}